import { AlertCircle, ArrowLeft, ArrowRight, LoaderCircle } from "lucide-react";
import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { listCatchmentStudies, type CatchmentStudy } from "../services/m3";
import { CatchmentMap } from "./CatchmentMap";

export function ManagerCatchmentDetail() {
  const { studyId } = useParams();
  const [study, setStudy] = useState<CatchmentStudy | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  useEffect(() => {
    listCatchmentStudies().then((items) => { const found = items.find((item) => item.id === studyId); if (!found) throw new Error("Study not found"); setStudy(found); setError(""); })
      .catch((reason: unknown) => setError(reason instanceof Error ? reason.message : "Could not load study"))
      .finally(() => setLoading(false));
  }, [studyId]);
  const summary = study?.summary;
  return <section className="manager-catchment-detail"><header className="page-heading"><div><p className="eyebrow">M3 Catchment Decision</p><h1>{study?.target_label ?? "Catchment study"}</h1><p>Coverage, team progress, and the effect on the property evaluation.</p></div><Link className="secondary-button" to="/manager/catchments"><ArrowLeft size={17} />Catchment requests</Link></header>
    {loading ? <div className="state-panel"><LoaderCircle className="spin" /> Opening catchment study</div> : null}
    {error ? <div className="inline-error" role="alert"><AlertCircle />{error}</div> : null}
    {study ? <div className="manager-catchment-layout"><div><CatchmentMap shapes={[{ geometry: study.target_geometry, color: "#782B90", label: "Target" }, { geometry: study.survey_geometry, color: "#20879A", label: "Remaining" }, ...study.zones.map((zone) => ({ geometry: zone.geometry, color: zone.status === "completed" ? "#16835f" : "#d89b00", label: zone.label }))]} lanes={study.lane_suggestions.map((lane) => ({ ...lane, included: study.zones.some((zone) => zone.suggested_lane_ids.includes(lane.id)) }))} surveyPoints={study.zones.flatMap((zone) => zone.submissions.map((item) => ({ latitude: item.latitude, longitude: item.longitude, flagged: item.location_mismatch })))} /><p className="map-source-line">Target geometry from {study.target_type === "area_report" ? "saved area report" : "property catchment radius"}. Mapped lanes from OSM via Overpass, fetched {study.lane_suggestions_fetched_at ? new Date(study.lane_suggestions_fetched_at).toLocaleString() : "not available"}.</p></div><article className="catchment-decision-card"><span className={`stage-chip ${study.status}`}>{study.status.replaceAll("_", " ")}</span><h2>Why this study?</h2><p>Requested for {study.target_type === "property" ? "a property evaluation" : "an analysed area"} to add lane-level field observations before a decision.</p><div className="catchment-facts"><span><small>Progress</small><strong>{study.progress_percent.toFixed(0)}%</strong></span><span><small>Prior coverage reused</small><strong>{study.reuse_coverage.toFixed(1)}%</strong></span><span><small>Remaining at request</small><strong>{Math.max(0, 100 - study.reuse_coverage).toFixed(1)}%</strong></span></div><p>{study.source_study_ids.length ? `${study.source_study_ids.length} recent completed studies contributed prior coverage; latest was ${study.reuse_age_days?.toFixed(1)} days old.` : "No sufficiently recent overlapping study contributed coverage."} Reuse requires {study.reuse_min_coverage.toFixed(0)}% within {study.reuse_max_age_days} days.</p><h3>Who's working on it?</h3>{study.zones.length ? study.zones.map((zone) => <div className="manager-zone-row" key={zone.id}><strong>{zone.label} · {zone.assignee_name}</strong><span>{zone.status.replaceAll("_", " ")} · {zone.submission_count} observations{zone.mismatch_review ? " · GPS review flagged" : ""}</span></div>) : <p>{study.status === "reused" ? "No new assignment was needed." : "Survey Manager has not assigned zones yet."}</p>}
      <h3>Findings and score change</h3>{summary ? <><p><strong>{summary.evidence_kind === "demo" ? "Demo/simulated" : "Field survey"}</strong> · {String(summary.observation_count ?? 0)} observations · {String(summary.coverage_percent ?? 0)}% target coverage.</p><p>{String(summary.limitations ?? "Field observations require manager interpretation.")}</p>{summary.previous_score != null && summary.updated_score != null ? <div className="score-change"><span>Before <b>{Number(summary.previous_score).toFixed(1)}</b></span><ArrowRight size={18} /><span>After <b>{Number(summary.updated_score).toFixed(1)}</b></span><small>Evaluation v{String(summary.evaluation_version)}</small></div> : null}</> : <p>Field summary is pending. No new property evaluation has been created by this study yet.</p>}{study.property_id ? <Link className="primary-button" to={`/manager/properties/${study.property_id}`}>Review evaluation history <ArrowRight size={17} /></Link> : <Link className="secondary-button" to={`/manager/reports/${study.area_report_id}`}>Open source area report</Link>}</article></div> : null}
  </section>;
}
