"""Exercise the local M1 report -> assignment -> property -> pipeline handoff."""

import io
import json
import sys

import httpx
from PIL import Image

BASE_URL = sys.argv[1] if len(sys.argv) > 1 else "http://localhost:8000/api/v1"
MANAGER = {"X-Demo-Role": "bd-manager", "X-Demo-User-Id": "bd-manager-1"}
EXECUTIVE = {"X-Demo-Role": "bd-executive", "X-Demo-User-Id": "bd-executive-1"}
OTHER_EXECUTIVE = {"X-Demo-Role": "bd-executive", "X-Demo-User-Id": "bd-executive-2"}


def main() -> None:
    client = httpx.Client(timeout=45)
    reports = client.get(f"{BASE_URL}/area-reports").raise_for_status().json()
    if not reports:
        raise RuntimeError("Run an M1 analysis first; no saved report is available")
    report = client.get(f'{BASE_URL}/area-reports/{reports[0]["id"]}').raise_for_status().json()
    if not report["suggestions"]:
        raise RuntimeError("The selected M1 report has no scouting suggestion")
    suggestion = report["suggestions"][0]
    assignment = client.post(f"{BASE_URL}/scout-assignments", headers=MANAGER, json={
        "area_report_id": report["id"], "suggestion_id": suggestion["id"],
        "assignee_id": "bd-executive-1", "instructions": "M2 automated walkthrough",
    }).raise_for_status().json()

    own = client.get(f"{BASE_URL}/scout-assignments", headers=EXECUTIVE).raise_for_status().json()
    other = client.get(f"{BASE_URL}/scout-assignments", headers=OTHER_EXECUTIVE).raise_for_status().json()
    assert any(item["id"] == assignment["id"] for item in own)
    assert not any(item["id"] == assignment["id"] for item in other)

    image = io.BytesIO()
    Image.new("RGB", (32, 24), "#FFF200").save(image, "JPEG")
    payload = {
        "latitude": suggestion["latitude"], "longitude": suggestion["longitude"],
        "address": f'M2 verification property, {report["area_name"]}',
        "rent_monthly": 120000, "size_sq_ft": 2000, "frontage_ft": 30, "road_width_ft": 40,
        "property_type": "street_shop", "floor_level": "ground", "visibility_rating": 4,
        "condition_rating": 4, "parking_available": True, "power_backup": True,
        "water_available": True, "notes": "Generated by verify_m2_flow.py",
    }
    prop = client.post(
        f'{BASE_URL}/scout-assignments/{assignment["id"]}/properties', headers=EXECUTIVE,
        data={"payload": json.dumps(payload)},
        files=[("photos", ("verification.jpg", image.getvalue(), "image/jpeg"))],
    ).raise_for_status().json()
    assert prop["evaluations"][-1]["scoring_version"] == "property-fitness-v1"
    assert client.get(f'{BASE_URL}/properties/{prop["id"]}', headers=OTHER_EXECUTIVE).status_code == 404

    moved = client.post(f'{BASE_URL}/properties/{prop["id"]}/stage', headers=MANAGER, json={
        "stage": "shortlisted", "reason": "Automated walkthrough verified the review handoff.",
    }).raise_for_status().json()
    reopened = client.get(f'{BASE_URL}/properties/{prop["id"]}', headers=MANAGER).raise_for_status().json()
    assert moved["stage"] == reopened["stage"] == "shortlisted"
    assert reopened["evaluations"][-1]["version"] == 1
    print(
        f'M2 flow passed: assignment={assignment["id"]} property={prop["id"]} '
        f'score={reopened["evaluations"][-1]["score"]} stage={reopened["stage"]}'
    )


if __name__ == "__main__":
    main()
