"""Exercise the local M1 report -> assignment -> property -> pipeline handoff."""

import io
import json
import sys

import httpx
from PIL import Image

BASE_URL = sys.argv[1] if len(sys.argv) > 1 else "http://localhost:8000/api/v1"
MANAGER = {"X-Demo-Role": "bd-manager", "X-Demo-User-Id": "bd-manager-1"}
EXECUTIVE = {"X-Demo-Role": "bd-executive", "X-Demo-User-Id": "bd-executive-1"}
OTHER_EXECUTIVE = {"X-Demo-Role": "bd-executive", "X-Demo-User-Id": "bd-executive-2"}


def check(condition: bool, message: str) -> None:
    if not condition:
        raise RuntimeError(message)


def main() -> None:
    client = httpx.Client(timeout=45)
    reports = client.get(f"{BASE_URL}/area-reports").raise_for_status().json()
    velachery = next((item for item in reports if item["area_name"].strip().lower() == "velachery"), None)
    if not velachery:
        raise RuntimeError("Run the M1 Velachery analysis first; no saved Velachery report is available")
    report = client.get(f'{BASE_URL}/area-reports/{velachery["id"]}').raise_for_status().json()
    if not report["suggestions"]:
        raise RuntimeError("The selected M1 report has no scouting suggestion")
    suggestion = report["suggestions"][0]
    assignment = client.post(f"{BASE_URL}/scout-assignments", headers=MANAGER, json={
        "area_report_id": report["id"], "suggestion_id": suggestion["id"],
        "assignee_id": "bd-executive-1", "instructions": "M2 automated walkthrough",
    }).raise_for_status().json()

    own = client.get(f"{BASE_URL}/scout-assignments", headers=EXECUTIVE).raise_for_status().json()
    other = client.get(f"{BASE_URL}/scout-assignments", headers=OTHER_EXECUTIVE).raise_for_status().json()
    check(any(item["id"] == assignment["id"] for item in own), "Assignment is missing for its owner")
    check(not any(item["id"] == assignment["id"] for item in other), "Assignment leaked to another executive")

    image = io.BytesIO()
    Image.new("RGB", (32, 24), "#FFF200").save(image, "JPEG")
    payload = {
        "latitude": suggestion["latitude"], "longitude": suggestion["longitude"],
        "address": f'M2 verification property, {report["area_name"]}',
        "rent_monthly": 120000, "size_sq_ft": 2000, "frontage_ft": 30, "road_width_ft": 40,
        "property_type": "street_shop", "floor_level": "ground", "visibility_rating": 4,
        "condition_rating": 4, "parking_available": True, "power_backup": True,
        "water_available": True, "notes": "Generated by verify_m2_flow.py",
    }

    unauthorized = client.post(
        f'{BASE_URL}/scout-assignments/{assignment["id"]}/properties', headers=OTHER_EXECUTIVE,
        data={"payload": json.dumps(payload)},
    )
    check(unauthorized.status_code == 404, "Another executive could submit to the assignment")

    for field, value in (("rent_monthly", 0), ("latitude", 0), ("longitude", 0)):
        invalid_payload = {**payload, field: value}
        invalid = client.post(
            f'{BASE_URL}/scout-assignments/{assignment["id"]}/properties', headers=EXECUTIVE,
            data={"payload": json.dumps(invalid_payload)},
        )
        check(invalid.status_code == 422, f"Invalid {field} was accepted")

    invalid_upload = client.post(
        f'{BASE_URL}/scout-assignments/{assignment["id"]}/properties', headers=EXECUTIVE,
        data={"payload": json.dumps(payload)},
        files=[("photos", ("fake.jpg", b"not an image", "image/jpeg"))],
    )
    check(invalid_upload.status_code == 422, "Invalid image content was accepted")

    prop = client.post(
        f'{BASE_URL}/scout-assignments/{assignment["id"]}/properties', headers=EXECUTIVE,
        data={"payload": json.dumps(payload)},
        files=[("photos", ("verification.jpg", image.getvalue(), "image/jpeg"))],
    ).raise_for_status().json()
    check(prop["evaluations"][-1]["scoring_version"] == "property-fitness-v1", "Unexpected scoring version")
    score = round(sum(metric["contribution"] for metric in prop["evaluations"][-1]["metrics"]), 1)
    check(score == prop["evaluations"][-1]["score"], "Saved property score does not equal metric contributions")
    check(client.get(f'{BASE_URL}/properties/{prop["id"]}', headers=OTHER_EXECUTIVE).status_code == 404, "Property leaked to another executive")

    duplicate = client.post(
        f'{BASE_URL}/scout-assignments/{assignment["id"]}/properties', headers=EXECUTIVE,
        data={"payload": json.dumps(payload)},
    )
    check(duplicate.status_code == 409, "Duplicate property submission was accepted")

    moved = client.post(f'{BASE_URL}/properties/{prop["id"]}/stage', headers=MANAGER, json={
        "stage": "shortlisted", "reason": "Automated walkthrough verified the review handoff.",
    }).raise_for_status().json()
    illegal = client.post(f'{BASE_URL}/properties/{prop["id"]}/stage', headers=MANAGER, json={
        "stage": "approved", "reason": "Boundary check must reject this skipped stage.",
    })
    check(illegal.status_code == 409, "Illegal shortlisted-to-approved transition was accepted")
    survey_requested = client.post(f'{BASE_URL}/properties/{prop["id"]}/stage', headers=MANAGER, json={
        "stage": "survey_requested", "reason": "Ready for the future M3 catchment survey handoff.",
    }).raise_for_status().json()
    reopened = client.get(f'{BASE_URL}/properties/{prop["id"]}', headers=MANAGER).raise_for_status().json()
    check(moved["stage"] == "shortlisted", "Shortlist stage was not persisted")
    check(survey_requested["stage"] == reopened["stage"] == "survey_requested", "Survey-requested stage was not persisted")
    check(reopened["evaluations"][-1]["version"] == 1, "Evaluation version changed unexpectedly")
    print(
        f'M2 flow passed: assignment={assignment["id"]} property={prop["id"]} '
        f'score={reopened["evaluations"][-1]["score"]} stage={reopened["stage"]}'
    )


if __name__ == "__main__":
    main()
